databases:
  - name: pynews-db
    plan: free
    databaseName: pynews

services:
  - type: web
    name: pynews-api
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pynews-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://python-news.vercel.app,https://python-news-hyo814s-projects.vercel.app"
  - type: cron
    name: pynews-crawler
    runtime: python
    plan: starter
    schedule: "0 0 * * 1"
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py crawl_news --days=7
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pynews-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
