# Generated by Django 6.0.3 on 2026-03-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(help_text='글 요약 (목록에 표시)')),
                ('content', models.TextField(help_text='본문 (Markdown 지원)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('author', models.CharField(default='PyNews 팀', max_length=100)),
                ('published_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='news.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
