# Generated by Django 6.0.3 on 2026-03-21 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='source_type',
            field=models.CharField(choices=[('editorial', '직접 작성'), ('crawled', '크롤링')], default='editorial', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, help_text='원본 링크 (크롤링 글)'),
        ),
    ]
