# Generated by Django 6.0.3 on 2026-03-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscriber_post_source_type_post_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_curated',
            field=models.BooleanField(default=False, help_text='큐레이션 승인 여부 (True인 글만 프론트에 노출)'),
        ),
    ]
